//JAR
export const JAR_ADD = "JAR_ADD";
//SAVINGS
export const SAVINGS_SUBTRACT = "SAVINGS_SUBTRACT";
export const SAVINGS_ADD = "SAVINGS_ADD";
export const SAVINGS_TRANSFER = "SAVINGS_TRANSFER";
//HISTORY
export const HISTORY_ADD = "HISTORY_ADD";
export const HISTORY_ADD_MULTIPLE = "HISTORY_ADD_MULTIPLE";
//CURRENCIES
export const SET_CURRENCIES = "SET_CURRENCIES";